version: '3.7'
services:
 domaindebito:
  image: domain-debito
  build:
   context: .
   dockerfile: Dockerfile
   args:
   - DATASOURCE_URL
   - DATASOURCE_USERNAME
   - DATASOURCE_PASSWORD
   - KAFKA_SERVER
  container_name: "domaindebito-container"
  restart:  always
  network_mode: host