echo off
echo "Inicializar Microsservico Dominio Debito"


set AWS_ACCESS_KEY=AKIAZL5Z25377GI6EY4G
set AWS_SECRET_KEY=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

set KAFKA_SERVER=172.17.172.63:29092
set KAFKA_GROUP=DISPAG
set KAFKA_CONSUMER_REGISTRAR_DEBITO_TOPIC=REGISTRARDEBITO
set KAFKA_PRODUCER_VERIFICAR_CREDOR_TOPIC=VERIFICARCREDOR


set DATASOURCE_USERNAME=programador
set DATASOURCE_PASSWORD=hidros

call java -jar -Xms768M -Xmx768M -Xmn256m -XX:MaxMetaspaceSize=64m -XX:+UseG1GC  target/domain-debito-2.6.3.jar
